---
- hosts: elkstack
  remote_user: root
  become: yes
  become_user: root
  roles:
  - { role: java }

- hosts: elasticsearch
  remote_user: root
  become: yes
  become_user: root
  roles:
  - { role: elasticsearch, tags: elasticsearch }

- hosts: kibana
  remote_user: root
  become: yes
  become_user: root
  roles:
  - { role: kibana, tags: kibana }

- hosts: logstash
  remote_user: root
  become: yes
  become_user: root
  roles:
  - { role: logstash, tags: logstash }

- hosts: metricbeat
  remote_user: root
  become: yes
  become_user: root
  roles:
  - { role: metricbeat, tags: metricbeat }
